// <auto-generated />
using System;
using AstarteDeviceSDKCSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstarteDeviceSDKCSharp.Migrations
{
    [DbContext(typeof(AstarteDbContext))]
    partial class AstarteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("AstarteDeviceSDKCSharp.Data.AstarteGenericPropertyEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("BsonValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("InterfaceMajor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("INTERFACE_FIELD_NAME");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AstarteGenericProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
