// <auto-generated />
using System;
using AstarteDeviceSDKCSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstarteDeviceSDKCSharp.Migrations
{
    [DbContext(typeof(AstarteDbContext))]
    [Migration("20230210125400_AddAstarteGenericPropertyEntryTable")]
    partial class AddAstarteGenericPropertyEntryTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("AstarteDeviceSDKCSharp.Data.AstarteGenericPropertyEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("BsonValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("INTERFACE_FIELD_NAME");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AstarteGenericProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
