// <auto-generated />
using AstarteDeviceSDKCSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstarteDeviceSDKCSharp.Migrations
{
    [DbContext(typeof(AstarteDbContext))]
    partial class AstarteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");
#pragma warning restore 612, 618
        }
    }
}
